apiVersion: apps/v1
kind: Deployment
metadata:
  name: ecommerce-backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ecommerce-backend
  template:
    metadata:
      labels:
        app: mynginx
    spec:
      containers:
      - image: acoursove2/k3s_backend
        name: k3s_backend
        ports:
        - containerPort: 80
